mkdir bin
cd bin
cmake -DBUILD_STATIC=OFF -DBUILD_TESTING=OFF -DUSE_INTERMEDIATE_OBJECTS_TARGET=OFF -DDISABLE_ASM=ON -DDISABLE_SSSE3=ON \
-DDISABLE_SSE4=ON -DDISABLE_CLMUL=ON -DDISABLE_SHA=ON -DDISABLE_AVX=ON -DDISABLE_AVX2=ON -DDISABLE_ARM_NEON=ON \
-DDISABLE_ARM_PMULL=ON -DDISABLE_ARM_SHA=ON -DDISABLE_ALTIVEC=ON -DDISABLE_POWER7=ON -DDISABLE_POWER8=ON \
-DDISABLE_POWER9=ON ..
cmake --build . -- -j 8